# Generated by Django 4.2.7 on 2025-10-08 05:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_alter_freelancerbidprofile_profile_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet')], default='razorpay', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('client_id', models.CharField(help_text='Client ID from Users Service', max_length=100)),
                ('freelancer_id', models.CharField(help_text='Freelancer ID from Users Service', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('payment_data', models.JSONField(blank=True, default=dict, help_text='Raw payment gateway response')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bids.bid')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bid', 'status'], name='payments_bid_id_e030df_idx'), models.Index(fields=['client_id', 'status'], name='payments_client__d2fdbb_idx'), models.Index(fields=['razorpay_payment_id'], name='payments_razorpa_c6ca42_idx'), models.Index(fields=['razorpay_order_id'], name='payments_razorpa_c67522_idx'), models.Index(fields=['created_at'], name='payments_created_e3a130_idx')],
            },
        ),
    ]
