# Generated by Django 4.2.7 on 2025-09-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_aiconversation_aimessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconversation',
            name='model_name',
            field=models.CharField(default='gpt-3.5-turbo', max_length=50),
        ),
    ]
