# Generated by Django 5.2.6 on 2025-09-30 06:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="FreelancerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills", models.JSONField(default=list)),
                ("experience_level", models.CharField(max_length=20)),
                ("years_of_experience", models.PositiveIntegerField(null=True)),
                (
                    "hourly_rate",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("total_projects_completed", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "freelancer_profiles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FreelancerScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.IntegerField(db_index=True, unique=True)),
                ("experience_score", models.FloatField(default=0)),
                ("education_score", models.FloatField(default=0)),
                ("review_score", models.FloatField(default=0)),
                ("completion_score", models.FloatField(default=0)),
                ("responsiveness_score", models.FloatField(default=0)),
                ("skills_score", models.FloatField(default=0)),
                ("final_score", models.FloatField(db_index=True, default=0)),
                ("score_tier", models.CharField(default="unrated", max_length=20)),
                ("ai_quality_score", models.FloatField(default=0)),
                ("ai_insights", models.TextField(blank=True, null=True)),
                ("strengths", models.JSONField(default=list)),
                ("improvements", models.JSONField(default=list)),
                ("calculation_version", models.CharField(default="1.0", max_length=10)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_freelancer_scores",
                "ordering": ["-final_score"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "final_score"],
                        name="ai_freelanc_user_id_78f257_idx",
                    ),
                    models.Index(
                        fields=["score_tier", "final_score"],
                        name="ai_freelanc_score_t_3b0b17_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_id", models.CharField(db_index=True, max_length=100)),
                ("user_id", models.IntegerField(db_index=True)),
                ("semantic_similarity", models.FloatField(default=0)),
                ("skill_match_percentage", models.FloatField(default=0)),
                ("combined_score", models.FloatField(db_index=True, default=0)),
                ("matched_skills", models.JSONField(default=list)),
                ("missing_skills", models.JSONField(default=list)),
                ("match_explanation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "ai_job_matches",
                "ordering": ["-combined_score"],
                "indexes": [
                    models.Index(
                        fields=["job_id", "combined_score"],
                        name="ai_job_matc_job_id_8b3c6a_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_job_matc_created_5d6b69_idx"
                    ),
                ],
                "unique_together": {("job_id", "user_id")},
            },
        ),
        migrations.CreateModel(
            name="ScoreHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.IntegerField(db_index=True)),
                ("score", models.FloatField()),
                ("score_breakdown", models.JSONField(default=dict)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_score_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "created_at"],
                        name="ai_score_hi_user_id_10b8cd_idx",
                    )
                ],
            },
        ),
    ]
