# Generated by Django 4.2.24 on 2025-09-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobattachment",
            options={},
        ),
        migrations.AlterField(
            model_name="jobattachment",
            name="file_size",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
