# Generated by Django 5.2.6 on 2025-09-20 04:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_bids_created', models.PositiveIntegerField(default=0)),
                ('total_bids_accepted', models.PositiveIntegerField(default=0)),
                ('total_bids_rejected', models.PositiveIntegerField(default=0)),
                ('total_bids_withdrawn', models.PositiveIntegerField(default=0)),
                ('average_bid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('average_delivery_time', models.FloatField(default=0)),
                ('top_categories', models.JSONField(blank=True, default=list)),
                ('top_skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bid_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FreelancerBidProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_bids', models.PositiveIntegerField(default=0)),
                ('accepted_bids', models.PositiveIntegerField(default=0)),
                ('completed_projects', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('cache_expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'freelancer_bid_profiles',
            },
        ),
        migrations.CreateModel(
            name='JobBidSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('total_bids', models.PositiveIntegerField(default=0)),
                ('pending_bids', models.PositiveIntegerField(default=0)),
                ('accepted_bids', models.PositiveIntegerField(default=0)),
                ('rejected_bids', models.PositiveIntegerField(default=0)),
                ('lowest_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('highest_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('average_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('average_delivery_time', models.FloatField(blank=True, null=True)),
                ('fastest_delivery', models.PositiveIntegerField(blank=True, null=True)),
                ('popular_skills', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_bid_summaries',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(help_text='Job ID from Jobs Service', max_length=100)),
                ('freelancer_id', models.CharField(help_text='Freelancer ID from Users Service', max_length=100)),
                ('bid_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly Rate'), ('milestone', 'Milestone Based')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('estimated_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('proposal', models.TextField(help_text="Freelancer's proposal/cover letter")),
                ('estimated_delivery', models.PositiveIntegerField(help_text='Estimated delivery in days')),
                ('questions', models.JSONField(blank=True, default=list, help_text="Freelancer's questions to client")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('client_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('client_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('client_feedback', models.TextField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'bids',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_id', 'status'], name='bids_job_id_281dcc_idx'), models.Index(fields=['freelancer_id', 'status'], name='bids_freelan_bf4d95_idx'), models.Index(fields=['status', 'created_at'], name='bids_status_9bd869_idx'), models.Index(fields=['created_at'], name='bids_created_ec08db_idx'), models.Index(fields=['expires_at'], name='bids_expires_b9b683_idx')],
                'unique_together': {('job_id', 'freelancer_id')},
            },
        ),
        migrations.CreateModel(
            name='BidAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bid_attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('portfolio', 'Portfolio Item'), ('document', 'Document'), ('certificate', 'Certificate'), ('reference', 'Reference'), ('other', 'Other')], default='document', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bids.bid')),
            ],
            options={
                'db_table': 'bid_attachments',
            },
        ),
        migrations.CreateModel(
            name='BidMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(help_text='User ID from Users Service', max_length=100)),
                ('sender_type', models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bids.bid')),
            ],
            options={
                'db_table': 'bid_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estimated_delivery_days', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_client', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='bids.bid')),
            ],
            options={
                'db_table': 'bid_milestones',
                'ordering': ['order'],
                'unique_together': {('bid', 'order')},
            },
        ),
        migrations.CreateModel(
            name='BidView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_id', models.CharField(help_text='Client ID from Users Service', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_views', to='bids.bid')),
            ],
            options={
                'db_table': 'bid_views',
                'indexes': [models.Index(fields=['bid', 'viewed_at'], name='bid_views_bid_id_75ca41_idx'), models.Index(fields=['viewer_id', 'viewed_at'], name='bid_views_viewer__4e1370_idx')],
            },
        ),
    ]
