# Generated by Django 4.2.7 on 2025-09-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerbidprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
